### ISSUE TITLE
cidr block in configuration

### ISSUE THREAD

**Issue by confiq** [moul/assh#304]
If I would have cidr block `10.2.0.0/16` that I want to put in the configuration I would write use wildcard
```yaml
hosts:
  10.2.*:
    Gateways: bastian
```
Is there another way that I can use specific cidr blocks?
