### ISSUE TITLE
Does not honour YAML syntax

### ISSUE THREAD

**Issue by renard** [moul/assh#318]
Let's use a simple yaml file to generate a configuration:

```yaml
hosts:
  host.example.com:
    Inherits: "tpl-example"
  host2.example.com: {Inherits: "tpl-example"}
 
templates:
  tpl-example:
    User: foo
```

The result is:

```
# This file was automatically generated by assh v2.8.0+dev
# on 2019-07-31 00:51:28 +0200 CEST, based on ~/.ssh/assh.yml
#
# more info: https://github.com/moul/assh

# host-based configuration
Host host.example.com
  Port 22
  User foo
  # Inherits: [tpl-example]

Host host2.example.com

# global configuration
Host *
  ProxyCommand assh connect --port=%p %h
```

As you can see `host2` inheritance does not seem to be honoured as is should be.

I use this syntax because sometime it is more handy to have one host per line.

I use:
```
assh --version
assh version 2.8.0+dev (HEAD)
```
