### ISSUE TITLE
User with command line Gateway is not working

### ISSUE THREAD

**Issue by victordidenko** [moul/assh#325]
Maybe I'm missing something, but I cannot find what...
I have simple config like this

```yaml
hosts:

  hosta:
    HostName: hosta.example.com
    User: hostauser

  hostb:
    HostName: hostb.example.com
    User: hostbuser
```
My local machine user, let's say, called `user`

When I connect to both hosts in separate (`ssh hosta` or `ssh hostb`), everything is working just fine.

But when I try to use some host as a gateway, for example `ssh hostb/hosta` — it uses _my local username_ `user` to connect to `hostb`, not `hostbuser` as specified in config!

If I manually specify user, like `ssh hostbuser@hostb/hosta` — this works.
