### ISSUE TITLE
Non array style hook is not working

### ISSUE THREAD

**Issue by miyamonz** [moul/assh#365]
some example in the README is written this style.
```yml
   #...
    Hooks:
      BeforeConnect: exec echo hai
```

but an error happens in my environment.
```
Error: failed to open config: yaml: unmarshal errors:
  line 90: cannot unmarshal !!str `exec ec...` into hooks.Hooks
```

but dashed array style works.
```yml
    Hooks:
      BeforeConnect:
      - exec echo hai
``` 

I don't know whether it's a bug or the document is wrong.
