### ISSUE TITLE
RemoteCommand parsed but not used?

### ISSUE THREAD

**Issue by ghostiam** [moul/assh#366]
I have a config:
```yaml
hosts:
  "domain.ltd":
    RemoteCommand: "tmux -CC attach || tmux -CC || true"
```

but in the final .ssh/config file this field does not appear and the command is not executed on the server.
