### ISSUE TITLE
How to change environment variables send to server

### ISSUE THREAD

**Issue by pendulm** [moul/assh#371]
[ssh_config](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html) has a option `SetEnv` to modify environment variable before connect. 

my config is something like this
```yaml
defaults:
  UserKnownHostsFile: /dev/null
  StrictHostKeyChecking: no
  LogLevel: QUIET
  ControlMaster: auto
  ControlPath: ~/.ssh/controlmasters/%C.sock
  ControlPersist: 600
  SetEnv: LANG en_US.UTF-8
```

but it dosn't works.  I found there isn't `SetEnv` option in [pkg/config/host.go](https://github.com/moul/assh/blob/1ff23beed69ec39ce7e3e65734257d240a9e6147/pkg/config/host.go).

Is there any way to configure this?
