### ISSUE TITLE
Dynamically change port depending on desired host

### ISSUE THREAD

**Issue by milkpirate** [moul/assh#372]
I'd like to have `ssh puppert123` to transform to something like this: `ssh -o ProxyCommand="ssh puppet-master nc %h %p" localhost -p 123`.

```
                                      localhost -p 123
                                       +-------------+
                                       |             |
                                       v             |
+---------+                    +-------+-------+     |
|         |   ssh puppet123    |               |     |
| my-host +------------------->+ puppet-master +-----+
|         |                    |               |
+---------+                    +---------------+
``` 

So I started with this:

```yaml
  puppet*:
    Port: <what to do>
    Hostname: localhost
    Gateways: puppet-master
```
