### ISSUE TITLE
BeforeConfigWrite and AfterConfigWrite does not seem to work

### ISSUE THREAD

**Issue by tomposmiko** [moul/assh#418]
It's like ignored:

assh.yml
```
---
defaults:
  hooks:
    BeforeConfigWrite:
      - 'exec cat ~/.ssh/tompos-config'
```
build:
```
$ assh config build
# This file was automatically generated by assh vn/a (n/a)
# on 2021-04-14 22:48:12 +0200 CEST, based on ~/.ssh/assh.yml
#
# more info: https://github.com/moul/assh

# host-based configuration
# global configuration
Host *
  ProxyCommand /home/tompos/go/bin/assh connect --port=%p %h
```

If I add other default options, they work, yml files can be included, just this one is missing.
What I want to achieve is basically adding another yaml file.
