### ISSUE TITLE
HostNames always come out commented

### ISSUE THREAD

**Issue by EugenMayer** [moul/assh#453]
when i have this `~/.ssh/assh.yml

```yaml
Hosts:
  myalias:
    HostName: bar
    User: me 
```

i get a commented out `HostName` when running `assh config build`

```
Host myalias
  User me
  # HostName: bar
```

Tested with `2.11` and `2.12` - running current stable manjaro. Thanks
