### ISSUE TITLE
SSH connection not closed

### ISSUE THREAD

**Issue by EugenMayer** [moul/assh#468]
After connecting to an SSH server and then disconnecting (exit) the connection is not closed (ps aux | grep ssh).
Also flushing with `ass socket flush` does not help.

My problem is that I used quiet some port forwarding and keeping those connections in the backup does block me from using the same port for a different connection

tried it with enabled or disable keepalive
```yaml
  TCPKeepAlive: yes
  ServerAliveInterval: 15
  ServerAliveCountMax: 3
```

Is this related to

```yaml
  ControlMaster: auto
  ControlPath: ~/.ssh/sockets/%h-%p-%r.sock
  ControlPersist: yes
```

I though the latter is rather for connection reused and should be closed when running `ass socket flush`

Latest stable arch / `assh version v2.11.3 (281772c0)`
