### ISSUE TITLE
ASSH with AWS SSM

### ISSUE THREAD

**Issue by sachajw** [moul/assh#554]
Dear Moul,

How would I use AWS SSM with ASSH? 
Is this even possible?
I was testing with this config, but it can't find the host?

With SSH, you open a port through a security group rule. 
AWS Systems Manager Session Manager utilizes an IAM role to connect with the instance.
https://aws.amazon.com/blogs/aws/new-session-manager/

Thank you,

```
defaults:
  ControlMaster: auto
  ControlPath: ~/.ssh.%h-%p-%r.sock
  ControlPersist: yes
  Hooks:
    # Automatically backup ~/.ssh/config
    BeforeConfigWrite:
      - 'exec set -x; cp {{.SSHConfigPath}} {{.SSHConfigPath}}.bkp'
    AfterConfigWrite:
      # Concat another `ssh_config` file with the one just generated by `assh`
      #- 'exec cat ~/.ssh/my-heroku-generated-config >> {{.SSHConfigPath}}'
      # Alert me with a Desktop notification
      - notify "{{.SSHConfigPath}} has been rewritten"
    OnConnect:
      # Log internal information to a file
      - exec printf '{{.}}' | jq . >> ~/.ssh/last_connected_host.txt
      # Alert me with a Desktop notification
      - notify New SSH connection to {{.Host.Prototype}} at {{.Stats.ConnectedAt}}
      # Write the host prototype to the terminal stderr
      - write New SSH connection to {{.Host.Prototype}}
    OnDisconnect:
      # write on terminal and in a Desktop notification some statistics about the finished connection
      - "write  SSH connection to {{.Host.HostName}} closed, {{.Stats.WrittenBytes }} bytes written in {{.Stats.ConnectionDuration}} ({{.Stats.AverageSpeed}}bps)"
      - "notify SSH connection to {{.Host.HostName}} closed, {{.Stats.WrittenBytes }} bytes written in {{.Stats.ConnectionDuration}} ({{.Stats.AverageSpeed}}bps)"

## ->> SSH over AWS SSM for i-87943f8ce654897
bastion-poc:
    hostname: i-087943f8ce654897
    ProxyCommand: sh -c "aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
    User: ubuntu
    IdentityFile: ~/.ssh/ssm-session.pem
    StrictHostKeyChecking: no

```
