### ISSUE TITLE
HostName fallback?

### ISSUE THREAD

**Issue by milkpirate** [moul/assh#670]
Hey,

I would like to have multiple `HostName`s and let `assh` check one after another to connect to. If one in the array fails, it should try the next given name automatically. Pretty much like the `Gateway` fallback logic but simply with different `HostName`s.

```
hosts:
  some-server:
    HostName:
      - 192.168.191.10
      - some-server
      - some.domain.name
```

So `assh` should do something like `ssh 192.168.191.10 || (ssh some-server || ssh some.domain.name)` automatically. Is that possible? Or addable without too much hazzle?
